### ISSUE TITLE
Extensibility of `getStyle`

### ISSUE THREAD

**Issue by mbarde** [eea/volto-columns-block#39]
First of all: Great addon, thank you for publishing this!

I have a feature request (or maybe you have an idea on how to solve our problem otherwise): We need to extend the `getStyle` function in `Styles/index.js` (basically a single line: setting text color depending on selected background color).

But because of the way this function is imported by the other components we cannot make use of Voltos overriding mechanism (https://training.plone.org/5/voltoaddons/07-misc-addons.html). I think if the function would be be outsourced in a not-`index.js` file this issue could be solved.

**Comment by tiberiuichim** [comment]
Meh... for some reason one of my colleagues copied some of the code of volto-block-style into this addon. In my initial design of volto-block-style, I envisioned it as an extensible and  something that could be integrated in other addons for any purpose, not just blocks. Maybe when I have the time I'll refactor this part.
