### ISSUE TITLE
Feature Request: Reverse wrap option

### ISSUE THREAD

**Issue by mbarde** [eea/volto-columns-block#44]
An additional bool field in the block settings. When set, columns break in reverse order on smaller screens.
Added this in my fork: https://github.com/mbarde/volto-columns-block/commit/146988173220dc45df525f01c1c3eac842d884ac

If you would like to adopt this feature I can create a PR.

**Comment by tiberiuichim** [comment]
@mbarde I've only seen your message now. Meh... sorry about this. A PR would sure be appreciated, and for sure accepted. Thanks!
