### ISSUE TITLE
On creation columns are evenly divided, regardless of selected proportions

### ISSUE THREAD

**Issue by kenmanheimer** [eea/volto-columns-block#57]
I always get 50 / 50 proportions when I create a two-column block, regardless of the choice I make. I then can use the `Layout` option in the Columns block sidebar dialog to assign the proportions I want, but it would be good to have the initial choice work. (The analogoous problem holds for the 25 / 50 / 25 three column choice.)

I'm using volto-columns-block 5.1.0 and Volto 16.3.0.

**Comment by FarooqAlaulddin** [comment]
Any Updates on this issue? well it work with older versions?

**Comment by tiberiuichim** [comment]
@FarooqAlaulddin no progress on this issue. If you're looking into it and solving it, we take PRs

**Comment by FarooqAlaulddin** [comment]
If you selected the 50/50 block then clicked on the main column block to edit its properties, you can see the property Layout. Change it to anything you want and it should work.

Example:

![image](https://user-images.githubusercontent.com/37892823/212621834-bb778836-4a3f-4c1f-b923-826a7c4a98fe.png)
![image](https://user-images.githubusercontent.com/37892823/212621916-f8497c04-2b39-4dcc-8311-8fee820e52e4.png)

This worked for me with 5.2.0

**Comment by wesleybl** [comment]
I think the issue here is that it doesn't respect what is selected on the "Select layout" screen:

![layout](https://user-images.githubusercontent.com/3297795/214158300-1ad5943d-27b8-4b6f-a3a0-e0ff05e2bcb0.gif)

Then you can change the field "Layout" that will work. But it should already work the first time.

**Comment by tiberiuichim** [comment]
Fixed by Wesley's PR https://github.com/eea/volto-columns-block/pull/63
